#!/bin/bash
# 
# **ENVIRONMENTAL PACKAGES SHOULD REMAIN STATIC FOR A GIVEN MODEL EXPERIMENT**
# 
# This shell script loads the necessary environmental packages and sets
# environmental variables/paths that WRF looks for during compile and
# when running.
# 
# Setup using modules on Cheyenne.
# 

module purge
module load ncarenv/1.3
module load intel/19.1.1
module load ncarcompilers/0.5.0
module load mpt/2.25
module load netcdf/4.8.1

export I_MPI_CC=icc
export I_MPI_CXX=icpc
export I_MPI_F90=ifort
export I_MPI_F77=ifort
export I_MPI_FC=ifort

# Necessary if remotely working from a Mac
export LC_ALL="en_US.UTF-8"

#FOR WRF

#WRF
export WRF_EM_CORE=1
export WRFIO_NCD_LARGE_FILE_SUPPORT=1

#NETCDF
# export NETCDF=$HOME/localsrc/netcdf
# export NETCDF_INC=$NETCDF/include
# export NETCDF_LIB=$NETCDF/lib
# export NETCDF_BIN=$NETCDF/bin
# # Copy over NETCDF files to common directory since netcdf C and FORTRAN modules are separate
# rm -rf $NETCDF
# mkdir -p localsrc
# mkdir $NETCDF
# mkdir $NETCDF/include
# mkdir $NETCDF/lib
# mkdir $NETCDF/bin
# cp -raf $EBROOTNETCDF/include/*  $NETCDF/include
# cp -raf $EBROOTNETCDF/lib64/* $NETCDF/lib
# cp -raf $EBROOTNETCDF/bin/* $NETCDF/bin
# cp -raf $EBROOTNETCDFMINFORTRAN/include/* $NETCDF/include
# cp -raf $EBROOTNETCDFMINFORTRAN/lib/* $NETCDF/lib
# cp -raf $EBROOTNETCDFMINFORTRAN/bin/* $NETCDF/bin

#HDF5
# export HDF5=$EBROOTHDF5

# FOR WPS

#jasper
# export JASPER=$EBROOTJASPER
# export JASPERLIB=$JASPER/lib
# export JASPERINC=$JASPER/include

#libpng
# export LIBPNG=$EBROOTLIBPNG
# export LIBPNGLIB=$LIBPNG/lib
# export LIBPNGINC=$LIBPNG/include

